name: gamersland
services:
  db:
    restart: always
    container_name: gamersland_db
    image: postgres
    healthcheck:
      test: [“CMD-SHELL”, “pg_isready”]
      interval: 1s
      timeout: 5s
      retries: 10
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - gamersland-vol:/var/lib/postgresql/data

    networks:
      - main
  api:
    restart: always
    container_name: gamersland_api
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "2998:2998"
    networks:
      - main

networks:
  main:
    driver: bridge
    external: true
volumes:
  gamersland-vol:
    external: true
