name: gamersland
services:
  db:
    restart: always
    container_name: gamersland_db
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - gamersland-vol:/var/lib/postgresql/data

    networks:
      - main
  api:
    restart: always
    container_name: gamersland_api
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    networks:
      - main

networks:
  main:
    driver: bridge
    external: true
volumes:
  gamersland-vol:
    external: true
